### ISSUE TITLE
Design event card as per spec

### ISSUE THREAD

**Issue by soniaturcotte** [tlwr/some-gallery-thing#8]
<img width="574" alt="Screenshot 2019-11-09 at 11 28 05" src="https://user-images.githubusercontent.com/19776089/68527888-1b2db200-02e4-11ea-86ef-47f6622786ae.png">

https://github.com/tlwr/some-gallery-thing/pull/9
https://github.com/tlwr/some-gallery-thing/pull/10

[] Mobile view typesizes

**Comment by soniaturcotte** [comment]
@jonheslop 

The design kind of works but it breaks down at certain points when the exhibition titles are ridiculously long. I don't want to just make the boxes larger, which will make all the normal exhibitions look dumb. 

What is the best approach here?

**Comment by jonheslop** [comment]
Tricky, do you always want the type size to be consistent across all the boxes? If not you could do and `if title.length > 40 characters, then smaller title size`?
